# Generated by Django 5.2.8 on 2025-11-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('course', models.CharField(choices=[('A', 'Bike'), ('B', 'Car'), ('K', 'Scooter')], max_length=1)),
                ('enrollment_date', models.DateField()),
                ('total_fee', models.IntegerField()),
                ('fees_paid', models.IntegerField(default=0)),
            ],
        ),
    ]
