# Generated by Django 5.2.8 on 2025-11-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
