# Generated by Django 5.2.8 on 2025-11-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0005_staff_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(default='NotPaid'),
            preserve_default=False,
        ),
    ]
