# Generated by Django 5.2.8 on 2025-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0006_student_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
