# Generated by Django 5.2.8 on 2026-03-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0007_alter_student_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('A', 'Bike(15 Days)'), ('B', 'Car(30 Days)'), ('K', 'Scooter(15 Days)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
